# Generated by Django 3.1.2 on 2021-10-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20211017_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='real_time_url',
        ),
    ]
