# Generated by Django 3.2.8 on 2021-10-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_alter_coin_id'),
        ('watchlist', '0003_alter_watchlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='coins',
            field=models.ManyToManyField(related_name='coins', to='coins.Coin'),
        ),
    ]
